### ISSUE TITLE
Bug when using <%+ within parent templates?

### ISSUE THREAD

**Issue by rgeronimi** [shiyanhui/hero#12]
Hello,

I have 1 web page, main.html, defined as such in Hero:

```
<%: func Main(w io.Writer) (int, error) %>
<%~ "page.html" %>
<%@ body { %>
Hello World!
<% } %>
```

Where page.html is defined as such:

```
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Test</title>
</head>
<body>
	<%@ body { %>
	<% } %>
	<%+ "google_analytics.html" %>
</body>
</html>
```

And google_analytics.html is defined as such (static content):
`<script>...</script>`

When all of that is compiled with Hero, it completes successfully, without any error message or warning. However, the google_analytics.html part is never included in the Golang code of main.html.go , it seems skipped:
```
...
_buffer.WriteString(`
Hello World!
`)

	_buffer.WriteString(`
</body>
</html>
`)
...
```

What shall be done? Is something missing somewhere in the templates? Or is it a bug in hero?

**Comment by shiyanhui** [comment]
Yes, it's a bug. I have fixed it. Thanks.

**Comment by rgeronimi** [comment]
Thats great.

Thanks,

Raphael
