### ISSUE TITLE
Non string variables don't seem to work

### ISSUE THREAD

**Issue by minaandrawos** [shiyanhui/hero#17]
It looks like there is a bug with variables that are not of string type so for example if I type: "<%=i x %>", the code generated used a variable called buffer which wasn't defined in the generated code and causes the code build to fail. When I look at the generated code, it seems like the variable name should be _buffer instead of buffer. Am I missing something?

**Comment by shiyanhui** [comment]
I'm unable to reproduce this. Could you please update Hero and try again?

**Comment by minaandrawos** [comment]
I tried again with a fresh go  get but no luck.  Here is a sample of the code that doesn't work:
 ```
  <% for _, animal := range animals { %>
              <tr>
               <td class="dinoname"><%=s animal.Nickname %></td>
                <td><%=i animal.Zone %></td>
                <td><%=i animal.Age %></td>
                <td class="dinodata"></td>
              </tr>
   <% } %> 
```
animal is a Go struct object that looks like this:
```
type Animal struct {
	ID         int  
	AnimalType string 
	Nickname   string 
	Zone       int    
	Age        int   
}
```
The code generated looks like this: 
```
	for _, animal := range animals {
		_buffer.WriteString(`
              <tr>
               <td class="dinoname">`)
		hero.EscapeHTML(animal.Nickname, _buffer)
		_buffer.WriteString(`</td>
                <td>`)
		hero.FormatInt(int64(animal.Zone), buffer)
		_buffer.WriteString(`</td>
                <td>`)
		hero.FormatInt(int64(animal.Age), buffer)
		_buffer.WriteString(`</td>
                <td class="dinodata"></td>
              </tr>
              `)
	}
```
The error I get complains about buffer not being a known type:

> undeclared name: buffer

When I look at the code I see that _buffer was declared but not buffer. Is there something I might be missing?

**Comment by shiyanhui** [comment]
May I see your function definition?

**Comment by minaandrawos** [comment]
Here is the function in the html file:

```
<%: func HandleMetrics(animals []databaselayer.Animal, w io.Writer) %>
<%~ "index.html" %>
<%@ body { %>
```
Here is the function definition in the auto-generated file:

```
func HandleMetrics(animals []databaselayer.Animal, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
```

**Comment by shiyanhui** [comment]
Sorry, still can't reproduce it. Here is the code: https://gist.github.com/shiyanhui/3c904a1a31ad1666b001de11300e0d18

Please make sure that you really update to the latest version.

    rm -rf $GOPATH/bin/hero
    rm -rf $GOPATH/src/github.com/shiyanhui/hero
    go get github.com/shiyanhui/hero

**Comment by minaandrawos** [comment]
Thank you for your quick response and help.  Things seem to be working for me now. I think you are right, it's because of the version.
