### ISSUE TITLE
What about scope of variables

### ISSUE THREAD

**Issue by nicola-spb** [shiyanhui/hero#20]
Can I put only some variables to sub template?
like this:

`<%+ "user.html"  $x $y $z>`

**Comment by shiyanhui** [comment]
No. Please read README for the template syntax.

**Comment by nicola-spb** [comment]
I read but I think it`s not good if I can change any variables in sub templates

**Comment by shiyanhui** [comment]
`<%+ %>` works just like `#include` in C/C++, it's just replace. It's not function, so there are no parameters pass.

**Comment by nicola-spb** [comment]
Ok. I understand. Thanks.
