### ISSUE TITLE
Single output file

### ISSUE THREAD

**Issue by viniciuschiele** [shiyanhui/hero#21]
Hi,

What do you think of having a parameter to compile the views into one single .go file? Having many .go files just make harder to find the .html file in the tree.

Thanks.

**Comment by shiyanhui** [comment]
You can generate the .go files to a different path with `-dest`. https://github.com/shiyanhui/hero#usage

**Comment by viniciuschiele** [comment]
Yeah, that is another way to work around this. 
Thanks
