### ISSUE TITLE
Qeustion

### ISSUE THREAD

**Issue by tural-esger** [shiyanhui/hero#34]
If I use buffer as you showed in example am I going to get higher performance than using io.writer? I am willing to use io.writer since it is much convenient and requires less code.

**Comment by shiyanhui** [comment]
No. If you use `io.writer` as a parameter in the defined function, hero will use buffer pool automatically in the generated code.

Example is here: https://github.com/shiyanhui/hero/blob/master/examples/app/template/userlistwriter.html.go

**Comment by tural-esger** [comment]
@shiyanhui Thank you very much!
