### ISSUE TITLE
Included template's block doesn't work

### ISSUE THREAD

**Issue by tural-esger** [shiyanhui/hero#39]
I have included navbar.html to my layout.html and created block inside navbar.html.  Then other page inherited from layout and I try to override these blocks, they don't work. Then I copied navbar and pasted inside layout it worked.

**Comment by shiyanhui** [comment]
Could you please show me your code?

**Comment by tural-esger** [comment]
_layout.html

`<!DOCTYPE html>
<html lang="en">

<head>
    <title><%@ title { %><% } %></title>
    <meta http-equiv="refresh" content="90">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="format-detection" content="telephone=no"/>
    <meta name="viewport" content="initial-scale=1, user-scalable=no, width=device-width">

    <meta name="mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-touch-fullscreen" content="yes">

    <meta name="apple-mobile-web-app-status-bar-style" content="#00caca">
    <meta name="msapplication-navbutton-color" content="#00caca">
    <meta name="theme-color" content="#00caca"/>

    <meta name="content-language" content="en_US"/>
    <meta name="medium" content="news"/>

    <meta name="robots" content="noodp, noydir, index, follow, archive"/>

    <meta name="yandex-verification" content="d0c180131372e174" />

    <meta name="audience" content="all"/>
    <meta name="distribution" content="global"/>
    <meta name="rating" content="General"/>
    <meta name="language" content="English"/>
    <meta name="contact" content="tural.asgar@gmail.com"/>
    <meta name="reply-to" content="tural.asgar@gmail.com"/>
    <meta name="copyright" content="engossip.com (c) 2017 All rights reserved"/>
    <meta name="web_author" content="Tural Asgar"/>

    <meta name="description" content="Learn English by speaking. Improve your speaking skill by talking to English learners using your Skype for free.">
    <meta name="keywords" content=" conversation partner learn spoken english e-pal free lessons improve speaking online exam fce cae cpe toefl ielts vocabulary words learning">

    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:site" content="@engossip.com"/>
    <meta name="twitter:title" content="engossip.com"/>
    <meta name="twitter:description" content="Learn English by speaking. Improve your speaking skill by talking to English learners using your Skype for free. No registeration required."/>
    <meta name="twitter:url" content="https://twitter.com/engossipcom"/>
    <meta name="twitter:domain" content="engossip.com"/>
    <meta name="twitter:creator" content="@TuralEsger"/>
    <meta name="twitter:image" content="/public/images/favicon.png"/>
    <meta name="twitter:account_id" content="907683763932598272"/>

    <meta property="fb:app_id" content=""/>
    <meta property="fb:pages" content="1402934379826532"/>
    <meta property="fb:admins" content="https://www.facebook.com/tur.esg"/>

    <meta property="og:locale" content="en_EN"/>
    <meta property="og:type" content="website"/>
    <meta property="og:title" content="engossip.com"/>
    <meta property="og:description" content="Learn English by speaking. Improve your speaking skill by talking to English learners using your Skype for free."/>
    <meta property="og:url" content="https://engossip.com"/>
    <meta property="og:site_name" content="engossip.com"/>

    <meta property="og:image" content="https://engossip.com/public/images/shareimage.jpg"/>
    <meta property="og:image:secure_url" content="https://engossip.com/public/images/shareimage.jpg"/>
    <meta property="og:image:type" content="image/jpg"/>
    <meta property="og:image:width" content="600"/>
    <meta property="og:image:height" content="600"/>

    <link rel="canonical" href="https://engossip.com">
    <link rel="alternate" href="http://engossip.com/"/>

    <link rel="shortcut icon" href="/public/images/favicon.png">
    <link rel="apple-touch-icon" href="/public/images/favicon.png">

    <link rel="stylesheet" href="/public/css/flags.min.css">
    <link rel="stylesheet" type="text/css" href="/public/css/pi.css"/>
    <link rel="stylesheet" type="text/css" href="/public/css/template.css"/>
    <link rel="stylesheet" type="text/css" href="/public/css/animate.css"/>
    <link rel="stylesheet" type="text/css" href="/public/icons/style.css"/>
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body>
 <%+ "_navbar.html" %>
<div class="container">
    <div class="row-10">
        <%@ body { %>
        <% } %>
    </div>
</div>
<footer class="main-footer pt-20 pb-20 text-center">
    <div class="clear">
        <span class="mr-10 d-in-block">Engossip.com © 2017</span>
        <span class="mr-10 d-in-block">All right reserved</span>
    </div>
    <a href="http://turalasgar.pro/" class="d-block" target="_blank" title="The Project by Tural Asgar">
        The Project by <strong>Tural Asgar</strong>
    </a>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="/public/js/custom.js"></script>
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-104245392-1', 'auto');
    ga('send', 'pageview');
</script>
</body>
</html>

`
_navbar.html

`<header class="main-header mb-30 pt-15 pb-15">
    <div class="container">
        <div class="row-0">
            <div class="col">
                <nav class="drop nav-menu float-left">
                    <button class="drop-toggle btn radius no-border hide-lg hide-md"><i class="icon-list-circle"></i></button>
                    <div class="drop-menu animation fadeInUp clear">
                        <a href="/how-to-use.html" class="menu-item tr-3s <%@ howtouseActive { %><% } %>" title="How To Use?">
                            <span>How To Use?</span>
                        </a>
                        <a href="/advice.html" class="menu-item tr-3s <%@ adviceActive { %><% } %>" title="Advice">
                            <span>Advice</span>
                        </a>
                        <a href="/about.html" class="menu-item tr-3s <%@ aboutActive { %><% } %>" title="About">
                            <span>About</span>
                        </a>
                        <a href="/contact.html" class="menu-item tr-3s <%@ contactActive { %><% } %>" title="Contact">
                            <span>Contact</span>
                        </a>
                    </div>
                </nav>
            </div>
            <div class="col logo-col text-center text-uppercase">
                <a href="/" title="Engossip.com" class="logo bold bg-ins"><i class="icon-language hide-xxs"></i> Engossip</a>
            </div>
            <div class="col">
                <div class="float-right">
                    <div class="drop social-menu float-left">
                        <button class="drop-toggle btn radius no-border hide-lg hide-md"><i class="icon-share"></i></button>
                        <div class="drop-menu right animation fadeInUp clear">
                            <a href="https://www.facebook.com/engossip/" class="menu-item tr-3s" target="_blank" title="Engossip Facebook">
                                <i class="icon-social-facebook"></i>
                                <span class="hide-lg hide-md ml-10">Facebook</span>
                            </a>
                            <a href="https://twitter.com/engossipcom" class="menu-item tr-3s" target="_blank" title="Engossip Twitter">
                                <i class="icon-social-twitter"></i>
                                <span class="hide-lg hide-md ml-10">Twitter</span>
                            </a>
                            <a href="https://www.instagram.com/engossipcom/" class="menu-item tr-3s" target="_blank" title="Engossip Instagram">
                                <i class="icon-social-instagram"></i>
                                <span class="hide-lg hide-md ml-10">Instagram</span>
                            </a>
                        </div>
                    </div>
                    <a href="/registration.html" class="btn bg-ins radius float-left ml-15">
                        <span class="hide-sm hide-xs hide-xxs">Registration</span>
                        <span class="hide-lg hide-md"><i class="icon-user-male"></i></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>`


about.html

`<%: func About(w io.Writer) %>

<%~ "_layout.html" %>

<%@ aboutActive { %>active<% } %>

<%@ title { %>About - find a partner to practise English speaking skills online for free!<% } %>

<%@ body { %>
<main class="main-content">
    <div class="container">
        <div class="page-header text-center mb-20">
            <h1 class="page-title"><strong>About</strong></h1>
            <div class="row-0">
                <div class="col lg-8 md-10 lg-ml-2 md-ml-1">
                    <ol class="breadcrumb d-in-block float-center">
                        <li><a href="/" title="Engossip.com - main page">Main Page</a></li>
                        <li><a href="/about.html" title="About">About</a></li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="row-0">
            <div class="col lg-8 md-10 lg-ml-2 md-ml-1">
                <div class="bg-gray p-15">
                    <div class="bg-white p-20">
                        <h2 class="content-title pb-20 mb-30 border-bottom">Use it, I built it for you.</h2>
                        <p>
                            <strong>engossip.com</strong> helps people find a partner in order to practise English
                            speaking skill. Finding someone to practise speaking is not easy, since most sites don't
                            give you Skype accounts. The majority of sites allow you to use their sites for free only
                            for a short period of time. While with engossip.com, there are no restrictions and time
                            limitations. You can use your own Skype account without registration Even after getting a
                            partner, you may not need to go back to our site (although other learners would be happy to see
                            you ☺ )
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<% } %>
`

The problem is I can't override. For example `<%@ aboutActive { %>active<% } %>` this one doesn't work.

**Comment by shiyanhui** [comment]
Hero will not extend blocks in sub-template for now. It's unreasonable and brings much inconvenience for template writing. I will correct as soon as possible. Thanks for this issue.

**Comment by shiyanhui** [comment]
Please update hero and test again.

**Comment by tural-esger** [comment]
Thank you very much. It works as expected. I thank you for your this awesome project and efforts you put on this. You are too responsive unlike others. I will use hero for other some projects. Big thanks.

**Comment by shiyanhui** [comment]
:)
