### ISSUE TITLE
how to use hero template engine with iris? 

### ISSUE THREAD

**Issue by aisq2008** [shiyanhui/hero#44]
I want to use hero template engine with iris in my project , but i don't know which is the best way to  use  them, somebody could write an example ? thank you!

iris address : https://github.com/kataras/iris/

**Comment by shiyanhui** [comment]
Hero only compiles the template to go code. So just call the generated functions in your iris app.

Take the same example in the readme,

Define your template like [this](https://github.com/shiyanhui/hero/blob/master/examples/app/template/userlistwriter.html) and generate your template to go code. You may use hero in iris like this,

```go
package main

import (
	"app/template"

	"github.com/kataras/iris"
)

func main() {
	app := iris.New()

	app.Get("/users", func(ctx iris.Context) {
		var userList = []string{
			"Alice",
			"Bob",
			"Tom",
		}
		template.UserList(userList, ctx)
	})

	app.Run(iris.Addr(":8080"))
}
```

**Comment by aisq2008** [comment]
thank you very much
