### ISSUE TITLE
Best way to handle Global Static Values

### ISSUE THREAD

**Issue by speedwheel** [shiyanhui/hero#50]
Let's say we have a struct with some global static values and we have to send this values to all the pages, should we include this struct on each func? for example:

template.User(GlobalStatic, UserData buffer)
template.Order(GlobalStatic, OrderData buffer)
template.Product(GlobalStatic, ProductData buffer)
etc...

It's this the right way?

**Comment by shiyanhui** [comment]
You can expose that struct via package and access it via package in the template. Just like the you do in golang.

**Comment by speedwheel** [comment]
Your are right, thanks!

**Comment by speedwheel** [comment]
What if I have a global value that is dynamic? for example some user session values that I want to send in all the templates?
