### ISSUE TITLE
Best way to handle Global Dynamic Values

### ISSUE THREAD

**Issue by speedwheel** [shiyanhui/hero#52]
I opened 1 month ago an issue on how to handle static global values, and now I am interested on what is the best way to handle dynamic global values (e.g. user session values ).
Since I can't access the session by exposing the package inside the template, I guess the best way is to send your session each time, for example let's say I need the user session data in the heqader on each page, then I would do this:

```go
template.UserPage(userSessionData)
template.HomePage(userSessionData)
template.ContactUs(userSessionData)
//etc.
```

Is this the 'hero way'?

**Comment by speedwheel** [comment]
@shiyanhui Any thoughts on this?

**Comment by shiyanhui** [comment]
There is no so called `hero way`. Just take the template as go code. So write the session code in the way writing go code when you write template.
