### ISSUE TITLE
关于Session之类的全局变量

### ISSUE THREAD

**Issue by higoalespn** [shiyanhui/hero#56]
我想问下，如果说一个模板header里面，要取session值，是不是只能在每次调用函数的时候传值，例如A页面对应func A，B页面对应func B，那是不是每个函数都要声明这个session的入参，然后传值进去。

**Comment by shiyanhui** [comment]
因为hero模板渲染后就是一个function, 所以把hero模板当成go代码就行了. 按照写go的思路来做就行. 所以可以这样做, 也可以用全局变量.
