### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by concatime** [shiyanhui/hero#57]
Hi there.
It would be great if we can import svg file into html. Something like `<%+ "image.svg" %>`.
If the link ends with `.svg`, just copy the content, without parsing.
Right now, I'm getting `image.svg not parsed`

**Comment by shiyanhui** [comment]
There is already option `extensions` for that. Please read the README for detail. Thanks.

**Comment by shiyanhui** [comment]
There is already option `extensions` for that. Please read the README for detail. Thanks.
