### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TechnicLab** [shiyanhui/hero#6]
Hello!
When i try to use your example, firstly I get this:
Parsing...
Generating...
Executing goimports...
Executing go vet...
vet: /Users/aruslan/Projects/Golang/project1/bin/test.html.go:7:12: "html" imported but not used
After that I am geeting same error from Go.

**Comment by jeromepeirick** [comment]
Same error for me.  
Also errors from tests:
go test lib/vendor/golang/src/github.com/shiyanhui/hero/parser_test.go 
\# command-line-arguments
lib/vendor/golang/src/github.com/shiyanhui/hero/parser_test.go:79: undefined: node
lib/vendor/golang/src/github.com/shiyanhui/hero/parser_test.go:85: undefined: TypeCode
lib/vendor/golang/src/github.com/shiyanhui/hero/parser_test.go:86: undefined: TypeExtend
lib/vendor/golang/src/github.com/shiyanhui/hero/parser_test.go:87: undefined: TypeEscapedValue
lib/vendor/golang/src/github.com/shiyanhui/hero/parser_test.go:91: undefined: newNode
lib/vendor/golang/src/github.com/shiyanhui/hero/parser_test.go:110: undefined: splitByEndBlock
lib/vendor/golang/src/github.com/shiyanhui/hero/parser_test.go:117: undefined: node
lib/vendor/golang/src/github.com/shiyanhui/hero/parser_test.go:118: undefined: newNode
lib/vendor/golang/src/github.com/shiyanhui/hero/parser_test.go:123: undefined: node
lib/vendor/golang/src/github.com/shiyanhui/hero/parser_test.go:241: undefined: node
lib/vendor/golang/src/github.com/shiyanhui/hero/parser_test.go:118: too many errors

**Comment by shiyanhui** [comment]
It's weired. Have you guys installed `goimports`?

**Comment by TechnicLab** [comment]
Oops, it looks like I forgot to set my PATH var. It will be great to add error when goimports command is unavailable.

**Comment by jeromepeirick** [comment]
I have goimports installed, but not in my default path.  Putting it in the path for my shell fixed the error.  Now to figure out why the server throws ERR_SSL_PROTOCOL_ERROR.  That's my problem, though.  Thanks for the guidance.

**Comment by Leryan** [comment]
Please add `goimports` as a requirement in the documentation. Thanks :)

**Comment by shiyanhui** [comment]
@Leryan OK, I will update it later.
