### ISSUE TITLE
Absolute Path of source on generated files causing code conflict

### ISSUE THREAD

**Issue by gusaul** [shiyanhui/hero#60]
hero will generate code with some commented line, on of them is source which contains absolute path of original html file [https://github.com/shiyanhui/hero/blob/master/examples/app/template/index.html.go#L2]([index.html.go#L2])
``` go
// source: /Users/Lime/Documents/workspace/GoProject/src/github.com/shiyanhui/hero/examples/app/template/index.html
```

it will causing code conflict when pushed to git due to diversity of absolute path on each computer.

it should be only relative path from `$GOPATH/src`, so it'll be 
 ``` go
// source: github.com/shiyanhui/hero/examples/app/template/index.html
```

thanks

**Comment by shiyanhui** [comment]
👍 👍
