### ISSUE TITLE
Invoking "go tool vet" directly is unsupported; use "go vet"

### ISSUE THREAD

**Issue by odiferousmint** [shiyanhui/hero#62]
Hello. Upon executing `hero -source="./"`, I get the following output:

```
Parsing...
Generating...
Executing goimports...
Executing go vet...
vet: invoking "go tool vet" directly is unsupported; use "go vet"
exit status 1
```

go version: `go1.12rc1 linux/amd64`

Is this going to be fixed?

https://golang.org/doc/go1.12#tools

**Comment by liua0** [comment]
hi, this issues is fixd

**Comment by shiyanhui** [comment]
Fixed.
