### ISSUE TITLE
有没有可以在server 层设置key的struct

### ISSUE THREAD

**Issue by jerry94test** [shiyanhui/hero#68]

**Comment by jerry94test** [comment]
```go
return hero.View{
        Name: "hello/name.html",
        Data: name,
    }
```
类似于这样。。。
这样的话 很方便集成到其他web 项目中去

**Comment by shiyanhui** [comment]
现在还没有 可以说下具体想法 后续看下是否可以加上这个特性

**Comment by jerry94test** [comment]
就是你现在的模板数据 是在 你生成的模板包里去 操作 按正常的思维
应该是 在 业务层就已经吧数据处理好 通过模板引擎去渲染
我觉得可以增加一个 template.Data(s map[string]interface)
然后在模板中直接使用 {{ .a }}  {{ a.c() }}
可以无缝集成到其他项目中
我用那个 gin + pong2（模板引擎）很头疼一点都不自由 
你这个项目很右特点

**Comment by shiyanhui** [comment]
现在就可以这样做啊 以example中的userlist为例 可以把你要渲染的数据(template.Data什么的)作为参数传进UserList, 比如    
<%: func UserList(userList []string, data template.Data, buffer *bytes.Buffer) %>这样的 不知道这样能不能满足你的需求

**Comment by jerry94test** [comment]
你没懂我意思啊 我这样来传值 我是不是需要这样来调用 {{ .data.a }} {{ data.c() }}

**Comment by jerry94test** [comment]
[你看看这个](https://github.com/kataras/iris/tree/master/hero)
[https://studyiris.com/example/hero/overview.html](https://studyiris.com/example/hero/overview.html)
我水平有限 刚学go 的。。。。

**Comment by jerry94test** [comment]
我懂了  就保持这个风格吧  感觉和以前使用 有很大区别

**Comment by jerry94test** [comment]
我感觉 你要多加几个例子

**Comment by shiyanhui** [comment]
对 这个用法和标准的template用法不一样 `{{ .a }}`这种写法不支持 可以看下hero的文档
