### ISSUE TITLE
one key multi type of structs

### ISSUE THREAD

**Issue by iDevoid** [shiyanhui/hero#73]
Hi, I found something unusual/unique when I was creating the unit test for generated `.html.go` file. this generated file has been used around half a year, and no error reported since
you may ask why unit test for generated file. but anyway

there's an `Args` which is map[string]interface{}
there are 2 html files included here. 
`<%~ "head.html" %>` inside `all.html` 

the generated file `all.html.go`, there are 
```
info.Args["samekey"].(strcut1).ID // from head.html
info.Args["samekey"].(struct2).Date // from all.html
```

I was confused, because I cannot set both struct in the same key on unit test.
so, I decided to change the other key inside the second html file, and generated (html.go) it again.

**Comment by shiyanhui** [comment]
>>> "I cannot set both struct in the same key on unit test."

Why can't you  set both? Could you please show me your test code?

**Comment by iDevoid** [comment]
Here is the example:
generated.html.go
```
line 200: int64(info.Args["samekey"].(NewStrcut).ID)
line 1500: info.Args["samekey"].(CompletelyDifferentStruct).CreateDate.(string)
```

the test:
```
args: args{
	info: Args{
		Title:             "The Title",
		Args: map[string]interface{}{
			"samekey" : NewStruct {
				ID : 1,
			},
		},
	},
},
```
resulting: 
panic: interface conversion: interface {} is nil, not template.CompletelyDifferentStruct [recovered]
... :1500 +0x353f


```
args: args{
	info: Args{
		Title:             "The Title",
		Args: map[string]interface{}{
			"samekey" : CompletelyDifferentStruct {
				CreateDate : "2019-09-09",
			},
		},
	},
},
```
resulting: 
panic: interface conversion: interface {} is nil, not template.NewStruct [recovered]
... :200 +0x353f


The HTML:
inside head.html
```
var ads_auth.shop_id="<%==i info.Args["adsAuth"].(AdsAuth).ShopID %>";
```

**Comment by shiyanhui** [comment]
I guess your test cases share the same variable args. And when test run, it got the wrong value. And it's dangerous asserting type of interface{} without boolean checking. You can do it like something as below,

```html
<% if v, ok := info.Args["samekey"].(CompletelyDifferentStruct) { %>
    <%==i v.CreateDate %>
<% } %>
```

**Comment by shiyanhui** [comment]
Closed for no response.
