### ISSUE TITLE
建议，是否可以提供一个开发模式

### ISSUE THREAD

**Issue by codingnan** [shiyanhui/hero#84]
开发中每次都要编译才能看到效果，每次微调都有几秒的延迟，这很影响节奏，也的确增加了开发时间（尤其是微调特别多的情况）。
能否增加一种开发模式，可以直接运行，而并不需要编译呢？
这个库其他地方我觉得都很不错。唯独这一点是个遗憾。

**Comment by shiyanhui** [comment]
这个库的原理就是把模板编译成go代码从而提高性能, 所以不重新编译运行是看不到效果的.

**Comment by codingnan** [comment]
收到，谢谢回复。
