### ISSUE TITLE
Imports are messed up

### ISSUE THREAD

**Issue by rohanthewiz** [shiyanhui/hero#9]
In the example
`go test` shows things that need to be imported are not

```~/go/src/github.com/shiyanhui/hero$ go test
Parsing...
Generating...
Executing goimports...
Executing go vet...
vet: /tmp/gohero/list.html.go:15:43: undeclared name: bytes
--- FAIL: TestGenerate (0.08s)
FAIL
exit status 1
```
Once the appropriate imports are added to `userlist.html` with  `<%!  import  %>` that error is fixed, however `index.html.go` and `user.html.go` are blank except for some unused exports which give errors.
`...template/index.html.go:7:12: "html" imported but not used`

**Comment by shiyanhui** [comment]
Please install `goimports` first.

**Comment by rohanthewiz** [comment]
I apologize. My failure to read instructions! Awesome job!
